import { FormField } from './FormModal';

export const modeleFields: FormField[] = [
  {
    name: 'name',
    label: 'Nom du modèle',
    type: 'text',
    required: true,
    placeholder: 'Entrez le nom du modèle',
  },
  {
    name: 'description',
    label: 'Description',
    type: 'textarea',
    required: true,
    placeholder: 'Décrivez le modèle',
    rows: 3,
  },
  {
    name: 'category',
    label: 'Catégorie',
    type: 'select',
    required: true,
    options: [
      { value: 'homme', label: 'Homme' },
      { value: 'femme', label: 'Femme' },
      { value: 'enfant', label: 'Enfant' },
      { value: 'accessoire', label: 'Accessoire' },
    ],
  },
  {
    name: 'price',
    label: 'Prix (FCFA)',
    type: 'number',
    required: true,
    min: 0,
    placeholder: 'Entrez le prix',
  },
  {
    name: 'status',
    label: 'Statut',
    type: 'select',
    required: true,
    options: [
      { value: 'disponible', label: 'Disponible' },
      { value: 'indisponible', label: 'Indisponible' },
      { value: 'en_revision', label: 'En révision' },
    ],
  },
  {
    name: 'imageUrl',
    label: 'Image du modèle',
    type: 'file',
    accept: 'image/*',
    helpText: 'PNG, JPG, GIF jusqu\'à 10MB',
  },
  {
    name: 'tags',
    label: 'Tags',
    type: 'tags',
    placeholder: 'Ajouter un tag',
  },
];

export const utilisateurFields: FormField[] = [
  {
    name: 'nom',
    label: 'Nom',
    type: 'text',
    required: true,
    placeholder: 'Entrez le nom',
  },
  {
    name: 'prenom',
    label: 'Prénom',
    type: 'text',
    required: true,
    placeholder: 'Entrez le prénom',
  },
  {
    name: 'email',
    label: 'Email',
    type: 'email',
    required: true,
    placeholder: 'Entrez l\'email',
  },
  {
    name: 'telephone',
    label: 'Téléphone',
    type: 'tel',
    required: true,
    placeholder: 'Entrez le numéro de téléphone',
  },
  {
    name: 'role',
    label: 'Rôle',
    type: 'select',
    required: true,
    options: [
      { value: 'admin', label: 'Administrateur' },
      { value: 'utilisateur', label: 'Utilisateur' },
      { value: 'client', label: 'Client' },
    ],
  },
  {
    name: 'adresse',
    label: 'Adresse',
    type: 'textarea',
    required: true,
    placeholder: 'Entrez l\'adresse',
    rows: 2,
  },
];

export const tailleurFields: FormField[] = [
  {
    name: 'nom',
    label: 'Nom',
    type: 'text',
    required: true,
    placeholder: 'Entrez le nom',
  },
  {
    name: 'prenom',
    label: 'Prénom',
    type: 'text',
    required: true,
    placeholder: 'Entrez le prénom',
  },
  {
    name: 'email',
    label: 'Email',
    type: 'email',
    required: true,
    placeholder: 'Entrez l\'email',
  },
  {
    name: 'telephone',
    label: 'Téléphone',
    type: 'tel',
    required: true,
    placeholder: 'Entrez le numéro de téléphone',
  },
  {
    name: 'nom_atelier',
    label: 'Nom de l\'atelier',
    type: 'text',
    required: true,
    placeholder: 'Entrez le nom de l\'atelier',
  },
  {
    name: 'specialite',
    label: 'Spécialité',
    type: 'select',
    required: true,
    options: [
      { value: 'homme', label: 'Vêtements pour hommes' },
      { value: 'femme', label: 'Vêtements pour femmes' },
      { value: 'enfant', label: 'Vêtements pour enfants' },
      { value: 'tous', label: 'Tous les types de vêtements' },
    ],
  },
  {
    name: 'experience',
    label: 'Années d\'expérience',
    type: 'number',
    required: true,
    min: 0,
    placeholder: 'Entrez le nombre d\'années d\'expérience',
  },
  {
    name: 'adresse',
    label: 'Adresse',
    type: 'textarea',
    required: true,
    placeholder: 'Entrez l\'adresse',
    rows: 2,
  },
  {
    name: 'photo',
    label: 'Photo',
    type: 'file',
    accept: 'image/*',
    helpText: 'PNG, JPG, GIF jusqu\'à 10MB',
  },
];

export const commandeFields: FormField[] = [
  {
    name: 'client',
    label: 'Client',
    type: 'select',
    required: true,
    options: [
      { value: '1', label: 'Amadou Diop' },
      { value: '2', label: 'Fatou Sow' },
      { value: '3', label: 'Moussa Diallo' },
    ],
  },
  {
    name: 'tailleur',
    label: 'Tailleur',
    type: 'select',
    required: true,
    options: [
      { value: '1', label: 'Mamadou Diop' },
      { value: '2', label: 'Aminata Sow' },
      { value: '3', label: 'Ibrahima Diallo' },
    ],
  },
  {
    name: 'modele',
    label: 'Modèle',
    type: 'select',
    required: true,
    options: [
      { value: '1', label: 'Boubou Traditionnel' },
      { value: '2', label: 'Robe de Mariée' },
      { value: '3', label: 'Costume d\'Enfant' },
    ],
  },
  {
    name: 'dateCommande',
    label: 'Date de commande',
    type: 'date',
    required: true,
  },
  {
    name: 'dateLivraison',
    label: 'Date de livraison prévue',
    type: 'date',
    required: true,
  },
  {
    name: 'statut',
    label: 'Statut',
    type: 'select',
    required: true,
    options: [
      { value: 'en_attente', label: 'En attente' },
      { value: 'en_cours', label: 'En cours' },
      { value: 'terminee', label: 'Terminée' },
      { value: 'annulee', label: 'Annulée' },
    ],
  },
  {
    name: 'prix',
    label: 'Prix (FCFA)',
    type: 'number',
    required: true,
    min: 0,
    placeholder: 'Entrez le prix',
  },
  {
    name: 'notes',
    label: 'Notes',
    type: 'textarea',
    placeholder: 'Ajoutez des notes ou des instructions spéciales',
    rows: 3,
  },
];

export const tissuFields: FormField[] = [
  {
    name: 'name',
    label: 'Nom du tissu',
    type: 'text',
    required: true,
    placeholder: 'Entrez le nom du tissu',
  },
  {
    name: 'description',
    label: 'Description',
    type: 'textarea',
    required: true,
    placeholder: 'Décrivez le tissu',
    rows: 3,
  },
  {
    name: 'type',
    label: 'Type',
    type: 'select',
    required: true,
    options: [
      { value: 'wax', label: 'Wax' },
      { value: 'bazin', label: 'Bazin' },
      { value: 'soie', label: 'Soie' },
      { value: 'coton', label: 'Coton' },
      { value: 'lin', label: 'Lin' },
      { value: 'autre', label: 'Autre' },
    ],
  },
  {
    name: 'couleur',
    label: 'Couleur',
    type: 'text',
    required: true,
    placeholder: 'Entrez la couleur principale',
  },
  {
    name: 'prix',
    label: 'Prix au mètre (FCFA)',
    type: 'number',
    required: true,
    min: 0,
    placeholder: 'Entrez le prix au mètre',
  },
  {
    name: 'stock',
    label: 'Stock disponible (mètres)',
    type: 'number',
    required: true,
    min: 0,
    placeholder: 'Entrez la quantité en stock',
  },
  {
    name: 'fournisseur',
    label: 'Fournisseur',
    type: 'text',
    required: true,
    placeholder: 'Entrez le nom du fournisseur',
  },
  {
    name: 'imageUrl',
    label: 'Image du tissu',
    type: 'file',
    accept: 'image/*',
    helpText: 'PNG, JPG, GIF jusqu\'à 10MB',
  },
  {
    name: 'tags',
    label: 'Tags',
    type: 'tags',
    placeholder: 'Ajouter un tag',
  },
];

export const accessoireFields: FormField[] = [
  {
    name: 'name',
    label: 'Nom de l\'accessoire',
    type: 'text',
    required: true,
    placeholder: 'Entrez le nom de l\'accessoire',
  },
  {
    name: 'description',
    label: 'Description',
    type: 'textarea',
    required: true,
    placeholder: 'Décrivez l\'accessoire',
    rows: 3,
  },
  {
    name: 'category',
    label: 'Catégorie',
    type: 'select',
    required: true,
    options: [
      { value: 'bijoux', label: 'Bijoux' },
      { value: 'chaussures', label: 'Chaussures' },
      { value: 'sacs', label: 'Sacs' },
      { value: 'ceintures', label: 'Ceintures' },
      { value: 'chapeaux', label: 'Chapeaux' },
      { value: 'autre', label: 'Autre' },
    ],
  },
  {
    name: 'prix',
    label: 'Prix (FCFA)',
    type: 'number',
    required: true,
    min: 0,
    placeholder: 'Entrez le prix',
  },
  {
    name: 'stock',
    label: 'Stock disponible',
    type: 'number',
    required: true,
    min: 0,
    placeholder: 'Entrez la quantité en stock',
  },
  {
    name: 'fournisseur',
    label: 'Fournisseur',
    type: 'text',
    required: true,
    placeholder: 'Entrez le nom du fournisseur',
  },
  {
    name: 'imageUrl',
    label: 'Image de l\'accessoire',
    type: 'file',
    accept: 'image/*',
    helpText: 'PNG, JPG, GIF jusqu\'à 10MB',
  },
  {
    name: 'tags',
    label: 'Tags',
    type: 'tags',
    placeholder: 'Ajouter un tag',
  },
];

export const evenementFields: FormField[] = [
  {
    name: 'name',
    label: 'Nom de l\'événement',
    type: 'text',
    required: true,
    placeholder: 'Entrez le nom de l\'événement',
  },
  {
    name: 'description',
    label: 'Description',
    type: 'textarea',
    required: true,
    placeholder: 'Décrivez l\'événement',
    rows: 3,
  },
  {
    name: 'type',
    label: 'Type d\'événement',
    type: 'select',
    required: true,
    options: [
      { value: 'mariage', label: 'Mariage' },
      { value: 'bapteme', label: 'Baptême' },
      { value: 'communion', label: 'Communion' },
      { value: 'anniversaire', label: 'Anniversaire' },
      { value: 'autre', label: 'Autre' },
    ],
  },
  {
    name: 'dateDebut',
    label: 'Date de début',
    type: 'date',
    required: true,
  },
  {
    name: 'dateFin',
    label: 'Date de fin',
    type: 'date',
    required: true,
  },
  {
    name: 'lieu',
    label: 'Lieu',
    type: 'text',
    required: true,
    placeholder: 'Entrez le lieu de l\'événement',
  },
  {
    name: 'organisateur',
    label: 'Organisateur',
    type: 'text',
    required: true,
    placeholder: 'Entrez le nom de l\'organisateur',
  },
  {
    name: 'contact',
    label: 'Contact',
    type: 'tel',
    required: true,
    placeholder: 'Entrez le numéro de téléphone',
  },
  {
    name: 'budget',
    label: 'Budget (FCFA)',
    type: 'number',
    required: true,
    min: 0,
    placeholder: 'Entrez le budget prévu',
  },
  {
    name: 'statut',
    label: 'Statut',
    type: 'select',
    required: true,
    options: [
      { value: 'planifie', label: 'Planifié' },
      { value: 'en_cours', label: 'En cours' },
      { value: 'termine', label: 'Terminé' },
      { value: 'annule', label: 'Annulé' },
    ],
  },
  {
    name: 'imageUrl',
    label: 'Image de l\'événement',
    type: 'file',
    accept: 'image/*',
    helpText: 'PNG, JPG, GIF jusqu\'à 10MB',
  },
  {
    name: 'notes',
    label: 'Notes',
    type: 'textarea',
    placeholder: 'Ajoutez des notes ou des détails supplémentaires',
    rows: 3,
  },
];

export const formationFields: FormField[] = [
  {
    name: 'name',
    label: 'Nom de la formation',
    type: 'text',
    required: true,
    placeholder: 'Entrez le nom de la formation',
  },
  {
    name: 'description',
    label: 'Description',
    type: 'textarea',
    required: true,
    placeholder: 'Décrivez la formation',
    rows: 3,
  },
  {
    name: 'type',
    label: 'Type de formation',
    type: 'select',
    required: true,
    options: [
      { value: 'couture', label: 'Couture' },
      { value: 'broderie', label: 'Broderie' },
      { value: 'design', label: 'Design de mode' },
      { value: 'business', label: 'Business de la mode' },
      { value: 'autre', label: 'Autre' },
    ],
  },
  {
    name: 'niveau',
    label: 'Niveau',
    type: 'select',
    required: true,
    options: [
      { value: 'debutant', label: 'Débutant' },
      { value: 'intermediaire', label: 'Intermédiaire' },
      { value: 'avance', label: 'Avancé' },
    ],
  },
  {
    name: 'dateDebut',
    label: 'Date de début',
    type: 'date',
    required: true,
  },
  {
    name: 'dateFin',
    label: 'Date de fin',
    type: 'date',
    required: true,
  },
  {
    name: 'duree',
    label: 'Durée (heures)',
    type: 'number',
    required: true,
    min: 1,
    placeholder: 'Entrez la durée en heures',
  },
  {
    name: 'formateur',
    label: 'Formateur',
    type: 'text',
    required: true,
    placeholder: 'Entrez le nom du formateur',
  },
  {
    name: 'prix',
    label: 'Prix (FCFA)',
    type: 'number',
    required: true,
    min: 0,
    placeholder: 'Entrez le prix de la formation',
  },
  {
    name: 'capacite',
    label: 'Capacité maximale',
    type: 'number',
    required: true,
    min: 1,
    placeholder: 'Entrez le nombre maximum de participants',
  },
  {
    name: 'lieu',
    label: 'Lieu',
    type: 'text',
    required: true,
    placeholder: 'Entrez le lieu de la formation',
  },
  {
    name: 'statut',
    label: 'Statut',
    type: 'select',
    required: true,
    options: [
      { value: 'planifie', label: 'Planifié' },
      { value: 'en_cours', label: 'En cours' },
      { value: 'termine', label: 'Terminé' },
      { value: 'annule', label: 'Annulé' },
    ],
  },
  {
    name: 'imageUrl',
    label: 'Image de la formation',
    type: 'file',
    accept: 'image/*',
    helpText: 'PNG, JPG, GIF jusqu\'à 10MB',
  },
  {
    name: 'prerequis',
    label: 'Prérequis',
    type: 'textarea',
    placeholder: 'Listez les prérequis pour cette formation',
    rows: 2,
  },
  {
    name: 'programme',
    label: 'Programme',
    type: 'textarea',
    required: true,
    placeholder: 'Décrivez le programme de la formation',
    rows: 4,
  },
];

export const moderationFields: FormField[] = [
  {
    name: 'type',
    label: 'Type de contenu',
    type: 'select',
    required: true,
    options: [
      { value: 'modele', label: 'Modèle' },
      { value: 'commentaire', label: 'Commentaire' },
      { value: 'utilisateur', label: 'Utilisateur' },
      { value: 'evenement', label: 'Événement' },
      { value: 'formation', label: 'Formation' },
    ],
  },
  {
    name: 'action',
    label: 'Action',
    type: 'select',
    required: true,
    options: [
      { value: 'approuver', label: 'Approuver' },
      { value: 'rejeter', label: 'Rejeter' },
      { value: 'supprimer', label: 'Supprimer' },
      { value: 'avertir', label: 'Avertir' },
      { value: 'suspendre', label: 'Suspendre' },
    ],
  },
  {
    name: 'raison',
    label: 'Raison',
    type: 'select',
    required: true,
    options: [
      { value: 'contenu_inapproprie', label: 'Contenu inapproprié' },
      { value: 'spam', label: 'Spam' },
      { value: 'harcelement', label: 'Harcèlement' },
      { value: 'violation_droits', label: 'Violation des droits d\'auteur' },
      { value: 'autre', label: 'Autre' },
    ],
  },
  {
    name: 'details',
    label: 'Détails',
    type: 'textarea',
    required: true,
    placeholder: 'Expliquez les détails de la décision de modération',
    rows: 4,
  },
  {
    name: 'duree_suspension',
    label: 'Durée de suspension (jours)',
    type: 'number',
    min: 1,
    max: 365,
    placeholder: 'Entrez la durée de suspension en jours',
    helpText: 'Uniquement pour l\'action "Suspendre"',
  },
  {
    name: 'notifier_utilisateur',
    label: 'Notifier l\'utilisateur',
    type: 'checkbox',
    helpText: 'Envoyer une notification à l\'utilisateur concerné',
  },
]; 